const data = [
  {
    title: 'Mr.',
    firstName: 'Jim',
    lastName: 'Halpert',
    age: 43,
    height: 75,
    weight: 180,
    gender: 'Male',
    city: 'Stanton, Pennsylvania',
    country: 'USA',
    image: '',
    favoriteQuote: "Everything I have I owe to this job… this stupid, wonderful, boring, amazing job.",
  },
  {
    title: 'Mrs.',
    firstName: 'Pamela',
    lastName: 'Halpert',
    age: 42,
    height: 66,
    weight: 126,
    gender: 'Female',
    city: 'Stanton, Pennsylvania',
    country: 'USA',
    image: '',
    favoriteQuote: "How is it possible that in five years, I've had two engagements and only one chair?",
  },
  {
    title: 'Mr.',
    firstName: 'Michael',
    lastName: 'Scott',
    age: 56,
    height: 69,
    weight: 160,
    gender: 'Male',
    city: 'Boulder, Colorado',
    country: 'USA',
    image: '',
    favoriteQuote: "I'm not superstitious, but I am a little stitious.",
  },
  {
    title: 'Mr.',
    firstName: 'Dwight',
    lastName: 'Schrute',
    age: 51,
    height: 74,
    weight: 185,
    gender: 'Male',
    city: 'Stanton, Pennsylvania',
    country: 'USA',
    image: '',
    favoriteQuote: "Today, smoking is going to save lives.",
  },
  {
    title: 'Mr.',
    firstName: 'Kevin',
    lastName: 'Malone',
    age: 43,
    height: 73,
    weight: 194,
    gender: 'Male',
    city: 'Stanton, Pennsylvania',
    country: 'USA',
    image: '',
    favoriteQuote: "Me think, why waste time say lot word, when few word do trick.",
  },
  {
    title: 'Mr.',
    firstName: 'Stanley',
    lastName: 'Hudson',
    age: 69,
    height: 71,
    weight: 210,
    gender: 'Female',
    city: 'Boulder, Colorado',
    country: 'USA',
    image: '',
    favoriteQuote: "Life is short. Drive fast and leave a sexy corpse. That’s one of my mottos.",
  },
  {
    title: 'Mr.',
    firstName: 'Andy',
    lastName: 'Bernard',
    age: 48,
    height: 71,
    weight: 180,
    gender: 'Male',
    city: 'Ithaca, New York',
    country: 'USA',
    image: '',
    favoriteQuote: 'Rit-dit-dit-do-doo!',
  },
  {
    title: 'Mrs.',
    firstName: 'Angela',
    lastName: 'Schrute',
    age: 47,
    height: 61,
    weight: 90,
    gender: 'Female',
    city: 'Stanton, Pennsylvania',
    country: 'USA',
    image: '',
    favoriteQuote: "I normally don't enjoy making people laugh.",
  },
  {
    title: 'Mrs.',
    firstName: 'Phyllis',
    lastName: 'Vance',
    age: 55,
    height: 67,
    weight: 200,
    gender: 'Female',
    city: 'Stanton, Pennsylvania',
    country: 'USA',
    image: '',
    favoriteQuote: "I'm glad Michael's getting help. He has a lot of issues, and he's stupid.",
  }
];

export default data;
