import * as React from 'react';

const data = [
  {
    title: 'Mr.',
    firstName: 'Jim',
    lastName: 'Halpert',
    age: 43,
    height: 75,
    weight: 180,
    gender: 'Male',
    city: 'Stanton',
    country: 'USA',
  },
  {
    title: 'Mrs.',
    firstName: 'Pamela',
    lastName: 'Halpert',
    age: 42,
    height: 66,
    weight: 126,
    gender: 'Female',
    city: 'Stanton',
    country: 'USA',
  },
  {
    title: 'Mr.',
    firstName: 'Michael',
    lastName: 'Scott',
    age: 56,
    height: 69,
    weight: 160,
    gender: 'Male',
    city: 'Boulder',
    country: 'Germany',
  },
  {
    title: 'Mr.',
    firstName: 'Dwight',
    lastName: 'Schrute',
    age: 51,
    height: 74,
    weight: 185,
    gender: 'Male',
    city: 'Stanton',
    country: 'USA',
  },
  {
    title: 'Mr.',
    firstName: 'Kevin',
    lastName: 'Malone',
    age: 43,
    height: 73,
    weight: 194,
    gender: 'Male',
    city: 'Stanton',
    country: 'USA',
  },
  {
    title: 'Mrs.',
    firstName: 'Holly',
    lastName: 'Flax',
    age: 48,
    height: 63,
    weight: 130,
    gender: 'Female',
    city: 'Boulder',
    country: 'USA',
  },
  {
    title: 'Mr.',
    firstName: 'Andy',
    lastName: 'Bernard',
    age: 48,
    height: 71,
    weight: 180,
    gender: 'Male',
    city: 'Ithaca',
    country: 'USA',
  },
  {
    title: 'Mrs.',
    firstName: 'Angela',
    lastName: 'Schrute',
    age: 47,
    height: 61,
    weight: 90,
    gender: 'Female',
    city: 'Stanton',
    country: 'USA',
  },
  {
    title: 'Mrs.',
    firstName: 'Phyllis',
    lastName: 'Vance',
    age: 55,
    height: 67,
    weight: 170,
    gender: 'Female',
    city: 'Stanton',
    country: 'USA',
  }
]

export default data;
